name: Update Dependencies

on:
  workflow_dispatch:

concurrency:
  group: upgrade-dependencies
  cancel-in-progress: true

jobs:
  dep-upgrade:
    permissions:
      pull-requests: write
      contents: write
    uses: edm00se/edm00se/.github/workflows/upgrade-deps.yml@master
    secrets: inherit
    with:
      nodever: '24'
